-- MySQL Script generated by MySQL Workbench
-- Thu 16 Jun 2016 12:14:05 AM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBCMMI_FINAL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBCMMI_FINAL` ;

-- -----------------------------------------------------
-- Schema DBCMMI_FINAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBCMMI_FINAL` DEFAULT CHARACTER SET utf8 ;
USE `DBCMMI_FINAL` ;

-- -----------------------------------------------------
-- Table `DBCMMI_FINAL`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBCMMI_FINAL`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `DBCMMI_FINAL`.`Usuarios` (
  `Id_Usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(75) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Tipo` ENUM('STUDENT', 'ADMIN') NOT NULL DEFAULT 'STUDENT',
  PRIMARY KEY (`Id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBCMMI_FINAL`.`Proyectos_Files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBCMMI_FINAL`.`Proyectos_Files` ;

CREATE TABLE IF NOT EXISTS `DBCMMI_FINAL`.`Proyectos_Files` (
  `Id_ProyectoFile` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Id_Proyecto` INT UNSIGNED NOT NULL,
  `MimeType` VARCHAR(45) NOT NULL,
  `Data` LONGBLOB NOT NULL,
  PRIMARY KEY (`Id_ProyectoFile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBCMMI_FINAL`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBCMMI_FINAL`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `DBCMMI_FINAL`.`Proyectos` (
  `Id_Proyecto` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Fecha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Proyecto`),
  UNIQUE INDEX `Id_Registro_UNIQUE` (`Id_Proyecto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `DBCMMI_FINAL`.`Usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBCMMI_FINAL`;
INSERT INTO `DBCMMI_FINAL`.`Usuarios` (`Id_Usuario`, `Matricula`, `Nombre`, `Apellidos`, `Correo`, `Tipo`) VALUES (NULL, '12345678', 'Daniel', 'Carlos Carlos', 'daniel.carlos.sc@itszapopan.edu.mx', 'ADMIN');
INSERT INTO `DBCMMI_FINAL`.`Usuarios` (`Id_Usuario`, `Matricula`, `Nombre`, `Apellidos`, `Correo`, `Tipo`) VALUES (NULL, '12345678', 'Selene', 'Palacios Montufar', 'selene.palacios.sc@itszapopan.edu.mx', 'ADMIN');
INSERT INTO `DBCMMI_FINAL`.`Usuarios` (`Id_Usuario`, `Matricula`, `Nombre`, `Apellidos`, `Correo`, `Tipo`) VALUES (NULL, '12345678', 'invitado', 'Desconocido', 'invitado@itszapopan.edu.mx', 'STUDENT');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
